### ISSUE TITLE
About LICENSE

### ISSUE THREAD

**Issue by wustho** [iscc/mobi#4]
Hello there, sorry, this is not really an issue. I am just asking about legal stuff.

 I write https://github.com/wustho/epr and epy which is a cli ebook reader. Currently I write it under MIT License. I am thinking to add MOBI support by adding option to import this awesome library which use GNU GPL v3 License... Do I need to change epy's License to GNU GPL v3 in order to use this library?

**Comment by titusz** [comment]
I am no legal expert. And I guess there are no easy answers. See: https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l

I would happily change the license to MIT if I could, but most of the code in this library is inherited from https://github.com/kevinhendricks/KindleUnpack which is GPL.

**Comment by wustho** [comment]
Thanks, I guess I'll just change mine to GPL... I just like MIT better because it has shorter read and more concise and less intimidating than GPL... I'll close this issue. Thanks again
