### ISSUE TITLE
How to customize the path to save the temp files

### ISSUE THREAD

**Issue by YangMingJerry** [iscc/mobi#5]
Hi guys, I wanna change the default path for saving the temp html file, which code should I look into? 

much obliged

**Comment by titusz** [comment]
The code uses the operating system specific functions for temporary directory creation. See: https://github.com/iscc/mobi/blob/master/mobi/extract.py

Extraction will return the path of the temporary folder/file. The suggested procedure would be to move the files from there to their target location or create a custom extract function.

**Comment by YangMingJerry** [comment]
This is extremely helpful for me, thanks alot. 

Have a nice day!
