### ISSUE TITLE
How to convert mobi file to epbu

### ISSUE THREAD

**Issue by YangMingJerry** [iscc/mobi#6]
Good day y'all

While reading your code, I noticed that the 'extract' method's intention was to extract mobi file and return path to epub file. But I can not find any interface or switch to save the epub file instead of html file. 

Would you please ellaborate how to modify the extract method or which file I shall look into for implementing the conversion from mobi to epub?

Thanks very much

Love your code

**Comment by titusz** [comment]
It depends on the mobi file. If it was created from an epub than you can extract it, else not.
